disable mockery and remove issue template

diff --git a/.github/workflows/check-generated.yml b/.github/workflows/check-generated.yml
--- a/.github/workflows/check-generated.yml
+++ b/.github/workflows/check-generated.yml
@@ -13,29 +13,30 @@ permissions:
   contents: read
 
 jobs:
-  check-mocks:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/setup-go@v3
-        with:
-          go-version: "1.19"
+  # Mocks have been disabled. See https://github.com/celestiaorg/celestia-core/pull/917
+  # check-mocks:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/setup-go@v3
+  #       with:
+  #         go-version: "1.19"
 
   #     - uses: actions/checkout@v3
 
-      - name: "Check generated mocks"
-        run: |
-          set -euo pipefail
+  #     - name: "Check generated mocks"
+  #       run: |
+  #         set -euo pipefail
 
-          make mockery
+  #         make mockery
 
-          if ! git diff --stat --exit-code ; then
-            echo ">> ERROR:"
-            echo ">>"
-            echo ">> Generated mocks require update (either Mockery or source files may have changed)."
-            echo ">> Ensure your tools are up-to-date, re-run 'make mockery' and update this PR."
-            echo ">>"
-            exit 1
-          fi
+  #         if ! git diff --stat --exit-code ; then
+  #           echo ">> ERROR:"
+  #           echo ">>"
+  #           echo ">> Generated mocks require update (either Mockery or source files may have changed)."
+  #           echo ">> Ensure your tools are up-to-date, re-run 'make mockery' and update this PR."
+  #           echo ">>"
+  #           exit 1
+  #         fi
 
   check-proto:
     runs-on: ubuntu-latest
